resource_types:

resources:

  - name: appcode
    type: git
    check_every: 24h
    webhook_token: ((github-enterprise.webhook-token))
    source:
      uri: https://github.com/Gopal95/demorepo
      username: Gopal95
      password: 0167e00f02bd24bbe62f6ba1d4a52be99d09cb8e
      branch: master

jobs:

  - name: build-and-publish-master
    serial: true
    plan:
      - get: appcode
        trigger: true
      - task: build
        file: appcode/ci/tasks/build.yml
